name: Python package


on:
  pull_request:
    types: [opened, edited, reopened, synchronize]
    paths:
      - 'services/example/**'

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/example/
    strategy:
      matrix:
        python-version: ["3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python -mpip install -r requirements.txt
      - name: Run app
        run: pytest app.py
      - uses: anchore/sbom-action@v0
        with:
          artifact-name: data-platform-svc-example.spdx
      - uses: anchore/sbom-action/publish-sbom@v0
        with:
          sbom-artifact-match: ".*\\.spdx$"
